title: "Mostafa Mehdipour Ghazi"
description: |
  Assistant Professor of AI
  Department of Computer Science
  University of Copenhagen
  ghazi(at)di.ku.dk
theme: jekyll-theme-minimal
avatar: "/photo-art.jpg"
